apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: exonk8s
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: exonk8s
    spec:
      containers:
      - name: exonk8s
        image: exonk8s:764dc42da93f433377caffd5d1f3c34b71d6dec3
        args:
        - foreground
        imagePullPolicy: Never
        ports:
        - containerPort: 4001
          protocol: TCP
        envFrom:
        - configMapRef:
            name: exonk8s-config
        - secretRef:
            name: exonk8s-secrets
      - name: postgres
        image: postgres:9.6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          name: postgresql
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: exonk8s-config
              key: PG_DATABASE
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: exonk8s-config
              key: PG_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: exonk8s-secrets
              key: PG_PASSWORD

---

apiVersion: v1
kind: Service
metadata:
  name: exonk8s
spec:
  ports:
  - name: exonk8s
    port: 80
    protocol: TCP
    targetPort: 4001
  selector:
    app: exonk8s
  sessionAffinity: None
  type: NodePort

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: exonk8s-config
data:
  RUN_MIGRATIONS: "true"
  REPLACE_OS_VARS: "true"
  PG_USERNAME: "exonk8s"
  PG_DATABASE: "exonk8s_prod"
  PG_HOSTNAME: "127.0.0.1"

---

apiVersion: v1
kind: Secret
metadata:
  name: exonk8s-secrets
type: Opaque
data:
  POD_COOKIE: Zm9vCg==
  PG_PASSWORD: c2VjcmV0cGFzc3dvcmQ=
